#!/bin/sh

if type "podman" > /dev/null; then
  container="podman"
fi

if type "docker" > /dev/null; then
  container="docker"
fi

if [[ -z "$container" ]]; then
  echo "Docker or Podman must be installed."
  exit
fi

# Build container image from dockerfile

$container build -t cuspike/container .

# Download distrobox to be able to use containers with GPU support without caring about podman, docker or CUDA Container Toolkit

curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --prefix $(pwd)/distrobox

export PATH=$(pwd)/distrobox/bin:$PATH

# Remove a previously created container if exists

distrobox stop cuspike-container --yes

distrobox rm cuspike-container --yes

# Create a new container from the newly built container image

distrobox create --name cuspike-container --image localhost/cuspike/container:latest --nvidia --yes
