#!/bin/sh
export PATH=$(pwd)/distrobox/bin:$PATH

distrobox enter cuspike-container \
          --additional-flags "--env PATH=/venv/bin:/usr/local/cuda/bin:$PATH" -- \
          bash -c "cd .. && bash"
